default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Run unit test.'
  lane :test do
    scan(
      device: 'iPhone 8',
      scheme: 'sample-ios-swift'
    )
  end
end
